### ISSUE TITLE
use onnx on Android

### ISSUE THREAD

**Issue by yanjingtp** [Picsart-AI-Research/MI-GAN#15]
<img width="335" alt="image" src="https://github.com/user-attachments/assets/6b843c86-485b-4687-9ff7-fa4cce4d3f95">

Hello,
Thank you for your work.
I use the onnx model on Android and the result is like this. Is there any problem?

**Comment by yanjingtp** [comment]
I have solved it

**Comment by huangbsolo** [comment]
在Android端遇到相同问题，填充区域是蒙版的九宫格形状，请问怎么解决的呢
