### ISSUE TITLE
problem when loading model

### ISSUE THREAD

**Issue by Marcelo5444** [Picsart-AI-Research/MI-GAN#2]
Error(s) in loading state_dict for Generator:
	Missing key(s) in state_dict: "synthesis.b8.conv1.upsample.insert_zeros.weight", "synthesis.b8.upsample.insert_zeros.weight", "synthesis.b16.conv1.upsample.insert_zeros.weight", "synthesis.b16.upsample.insert_zeros.weight", "synthesis.b32.conv1.upsample.insert_zeros.weight", "synthesis.b32.upsample.insert_zeros.weight", "synthesis.b64.conv1.upsample.insert_zeros.weight", "synthesis.b64.upsample.insert_zeros.weight", "synthesis.b128.conv1.upsample.insert_zeros.weight", "synthesis.b128.upsample.insert_zeros.weight", "synthesis.b256.conv1.upsample.insert_zeros.weight", "synthesis.b256.upsample.insert_zeros.weight". 
	Unexpected key(s) in state_dict: "synthesis.b8.conv1.upsample.filter_const", "synthesis.b8.upsample.filter_const", "synthesis.b16.conv1.upsample.filter_const", "synthesis.b16.upsample.filter_const", "synthesis.b32.conv1.upsample.filter_const", "synthesis.b32.upsample.filter_const", "synthesis.b64.conv1.upsample.filter_const", "synthesis.b64.upsample.filter_const", "synthesis.b128.conv1.upsample.filter_const", "synthesis.b128.upsample.filter_const", "synthesis.b256.conv1.upsample.filter_const", "synthesis.b256.upsample.filter_const".

**Comment by AndranikSargsyan** [comment]
Please make sure to use the updated model weights from here: 
https://drive.google.com/drive/folders/1xNtvN2lto0p5yFKOEEg9RioMjGrYM74w

Also make sure you are on the latest version of the code.
