### ISSUE TITLE
problem when export inference model

### ISSUE THREAD

**Issue by FelixEdwards** [Picsart-AI-Research/MI-GAN#3]
Hi
Thanks for your work.
I am expressing that when I use the export_inference_model.py file to attempt to convert the pkl file to onnx, I encountered an error. Could you please help me identify the issue?

```
File "MI-GAN/scripts/export_inference_model.py", line 119, in main
    resume_data = pickle.Unpickler(f).load()
ModuleNotFoundError: No module named 'lib.model_zoo.simpleinpainting'
```

**Comment by AndranikSargsyan** [comment]
Hello. I have just updated the repo. The issue should be resolved if you pull the latest version of the code.

**Comment by FelixEdwards** [comment]
thanks a lot.
