### ISSUE TITLE
How to train on custom dataset If I  didn't have Co-Mod-GAN pretrain model on this dataset ?

### ISSUE THREAD

**Issue by Jamescallow** [Picsart-AI-Research/MI-GAN#4]

**Comment by R1ckLou** [comment]
> _No description provided._
Hello, I also want to run the training code on the custom dataset, have you implemented the training?

**Comment by AndranikSargsyan** [comment]
Hello. I will add Co-Mod-GAN training ability as soon as I get a chance (probably early next year).

**Comment by HirokiMorita** [comment]
Dear person in charge

Nice to meet you.
 I am from a company that deals with imaging services and I am interested in the performance of MIGAN.
We are considering using it in our services, but this would require fine tuning in line with our service environment. 
The current code structure makes it difficult to train with our own training data, 
and I would be interested to hear if you have made any progress on the training code.

Thank you in advance for your confirmation.
Best Regards,

Hiroki Morita

**Comment by Hoanha2101** [comment]
Are you OK???, Now, in 2024, although your code application is very good, code structure is very different to understand, and how to train with custom data. I hope you come back and improve your code more clearly so that your code is truly public.

**Comment by dangchau2111** [comment]
Dear person in charge 

I'm waiting for you sir. Your MIGAN is so perfect. 

Best Regards,

Dang Chau

**Comment by AndranikSargsyan** [comment]
Hello everyone! The Co-Mod-GAN training code and instructions have been added to the repository. Sorry for the delay.
