### ISSUE TITLE
IOPaint add MI-GAN model support

### ISSUE THREAD

**Issue by Sanster** [Picsart-AI-Research/MI-GAN#6]
Hi, thank you for open sourcing your model and code. I have added this model to my open source project and it can be installed and used in the following way:

```bash
pip install iopaint
iopaint start --model migan
```

open http://localhost:8080/

More info about the tool: https://github.com/Sanster/lama-cleaner/releases/tag/iopaint-1.0.0b2

**Comment by AndranikSargsyan** [comment]
Hi. Your open-source project is really cool. Thank you for adding our model!
