### ISSUE TITLE
Bad results

### ISSUE THREAD

**Issue by sansavision** [Picsart-AI-Research/MI-GAN#9]
Without composition, just looking at the output of places 512 model, it looks so horrible, even the inpainted area doesn't seem up-to-par with the paper. Look at this example 
**Here's the original image**
![img](https://github.com/Picsart-AI-Research/MI-GAN/assets/90557503/d116dea7-ff77-4c84-878b-e7d559649944)

**Here's the mask**
![mask](https://github.com/Picsart-AI-Research/MI-GAN/assets/90557503/a6edc1ea-e1d5-477c-81bd-951015afa250)

**Here's the direct output (without composition)**
![debug](https://github.com/Picsart-AI-Research/MI-GAN/assets/90557503/9026d94f-3031-4ed8-bb7c-e24159ce1904)

Looks so horrible, how did you report such a low FID score?

**Comment by AndranikSargsyan** [comment]
Hello. This method is not intended to be used without composition. If you take a look into the training strategy for this method, you'll see that the generated result is being blended with the original image before being passed as an input to the discriminator. So learning to copy the known region from the input to the output is not included in the objective of MI-GAN. 
In summary, blending with the original image is a necessary part for MI-GAN (at least with the training strategy described in the paper and implemented in this codebase), and all reported metrics were computed with blending, for all methods in comparison.
